// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyB9Bl53X5ZoeWnyfh2wPcOKf8YxjDpM1Ic",
      authDomain: "votechains.firebaseapp.com",
      projectId: "votechains",
      storageBucket: "votechains.appspot.com",
      messagingSenderId: "698106067593",
      appId: "1:698106067593:web:58fdd2e295951244e3e458",
      measurementId: "G-GBJVFNPSRJ");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpAG0_mG0prZc4XIIv1F01zmx3dQ3iGak',
    appId: '1:698106067593:android:02bee1728b11ba9fe3e458',
    messagingSenderId: '698106067593',
    projectId: 'votechains',
    storageBucket: 'votechains.appspot.com',
  );
}
